/**
 * ПРИЁМКА ИТЕРАЦИИ 1 — станок кладёт девбокс в живой репозиторий.
 *
 * Не unit и не мок: обвес девбокса ставится в `node_modules` чистого временного
 * репозитория ровно так, как его положил бы npm, дверь зовётся своей публичной
 * поверхностью, и файлы уезжают на настоящий диск. Эталон — ЖИВОЙ
 * `.devcontainer` этого репозитория (`tasker:BASER2-18`).
 *
 * Проверяются ПЕРЕХОДЫ, а не устойчивые состояния: в устойчивом состоянии всё
 * сходится с первого раза, а дефекты этого продукта дважды лежали в переходах.
 * Поэтому каждый describe ниже — это событие, а не снимок.
 *
 * ── ЧТО ЭТОТ ПРОГОН НАШЁЛ ──────────────────────────────────────────────────
 *
 * Два блокера итерации, оба вне зоны двери и оба зафиксированы здесь ПРОГОНОМ,
 * а не рассуждением. Первый describe их и держит: он проверяет не то, что всё
 * хорошо, а то, что происходит на самом деле. Убрать его можно будет тогда,
 * когда блокеры закроются, — и тогда он сам покраснеет.
 */

import { afterEach, describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  installDevbox,
  liveArtifact,
  makeArtifactOwnable,
  withoutMarker,
  DEVBOX_PACKAGE,
  type Consumer,
} from './devbox.fixture.js';
import { run } from './run.js';
import { readOwnership } from '@omnifield/baser-materialize';

const LOCK = '.devcontainer/devcontainer-lock.json';
const LIVE = '.devcontainer/devcontainer.json';

const CONFIG = {
  formVersion: 1,
  sources: [{ use: DEVBOX_PACKAGE, presets: ['omnifield'] }],
};

let consumer: Consumer | null = null;

afterEach(() => {
  consumer?.cleanup();
  consumer = null;
});

/** Чистое дерево с поставленным обвесом девбокса. */
function clean(options: { existing?: Record<string, string> } = {}): Consumer {
  consumer = installDevbox({ config: CONFIG, ...options });
  return consumer;
}

/** То же, но с раскладкой, которую движок умеет брать во владение. */
function ownable(options: { existing?: Record<string, string> } = {}): {
  box: Consumer;
  dest: string;
} {
  const box = clean(options);
  return { box, dest: makeArtifactOwnable(box) };
}

describe('БЛОКЕРЫ, найденные прогоном живого обвеса', () => {
  it('живой devcontainer.json НЕ ЛОЖИТСЯ: это JSONC, а движок его пометить не может', async () => {
    const box = clean();

    const result = await run({ command: 'apply', cwd: box.root });

    // Спецификация Dev Containers разрешает комментарии, и обвес их несёт.
    // Движок для расширения `.json` умеет ровно один способ доказать владение —
    // ключ `"//"` в РАЗОБРАННОМ JSON, — поэтому берёт отказ на разборе.
    const conflict = result.plan?.conflicts.find((item) => item.dest === LIVE);
    expect(conflict?.kind).toBe('unmarkable-dest');
    expect(conflict?.detail.unmarkable).toBe('content-shape');

    // И раз план заблокирован — не легло НИЧЕГО, включая соседний артефакт,
    // который сам по себе пометился бы без проблем. Применение целиком либо
    // никак: это правильно, и это ровно та причина, по которой итерация не
    // доезжает. Зона движка: `.json` обязан уметь JSONC.
    expect(result.status).toBe('blocked');
    expect(box.exists(LIVE)).toBe(false);
    expect(box.exists(LOCK)).toBe(false);
  });

  it('render: false НЕ ложится байт в байт: движок вписывает маркер владения', async () => {
    const { box } = ownable();
    await run({ command: 'apply', cwd: box.root });

    const template = readFileSync(
      join(box.sourceRoot, 'template/devcontainer-lock.json'),
      'utf-8',
    );
    const landed = box.read(LOCK) ?? '';

    // Форма обещает: `render: false` — «файл копируется байт в байт», для
    // бинарного и для пинов по digest. Движок же метит КАЖДЫЙ артефакт, и для
    // JSON это ключ `"//"` плюс переслаивание через `JSON.stringify`.
    expect(landed).not.toBe(template);
    expect(landed).toContain('"//"');
    // Тело при этом не потеряно — расходится только служебная запись.
    expect(withoutMarker(LOCK, landed)).toBe(template);
    // Из этого же следует, что «render: false для бинарного» сегодня
    // невозможно вовсе: неразмечаемый класс движок во владение не берёт.
  });
});

describe('переход: чистое дерево → обвес разложен', () => {
  it('артефакт лёг на ДИСК, помечен движком и сходится с живым эталоном', async () => {
    const { box, dest } = ownable();

    const result = await run({ command: 'apply', cwd: box.root });

    expect(result.status).toBe('applied');
    expect(result.writes.map((write) => write.path).sort()).toEqual([
      LOCK,
      dest,
    ]);

    const landed = box.read(dest);
    expect(landed).not.toBeNull();

    // Владение доказуемо — маркер утверждает, из какого шаблона артефакт.
    const body = withoutMarker(dest, landed as string);
    expect(landed).toContain('Generated by');
    expect(landed).toContain('"src":"devcontainer.json.ejs"');

    // Сверка с ЖИВЫМ файлом этого репозитория. Единственное расхождение то же,
    // что назвала проба формы: во второй строке живого файла руками написано
    // «baser devbox», а обвес подставляет туда настройку `name`.
    expect(withoutLine(body, 2)).toBe(withoutLine(liveArtifact(LIVE), 2));
    expect(body.split('\n')[1]).toContain('baser-devbox');
    expect(liveArtifact(LIVE).split('\n')[1]).toContain('baser devbox');
  });

  it('подстановка не экранирует под HTML — кавычка осталась кавычкой', async () => {
    const { box, dest } = ownable();
    await run({ command: 'apply', cwd: box.root });
    const landed = box.read(dest) ?? '';

    expect(landed).not.toContain('&#34;');
    expect(landed).toContain('"--network=omnifield-gateway"');
  });
});

describe('переход: тот же прогон второй раз', () => {
  it('сошлось — ни шага, и диск не тронут', async () => {
    const { box, dest } = ownable();
    await run({ command: 'apply', cwd: box.root });
    const after = box.read(dest);

    const again = await run({ command: 'apply', cwd: box.root });

    // Операционное определение сходимости: второй прогон не порождает шагов.
    expect(again.status).toBe('converged');
    expect(again.plan?.steps).toEqual([]);
    expect(again.writes).toEqual([]);
    expect(box.read(dest)).toBe(after);
  });
});

describe('переход: пресет убран из конфига', () => {
  it('значение возвращается к дефолту обвеса, и артефакт догоняет', async () => {
    const { box, dest } = ownable();
    await run({ command: 'apply', cwd: box.root });
    expect(box.read(dest)).toContain('--network=omnifield-gateway');

    box.write(
      'baser.json',
      `${JSON.stringify(
        { formVersion: 1, sources: [{ use: DEVBOX_PACKAGE }] },
        null,
        2,
      )}\n`,
    );

    const plan = await run({ command: 'plan', cwd: box.root });
    const network = plan.settings.find((setting) => setting.key === 'network');
    // Цепочка укоротилась до одного звена: движения больше нет.
    expect(network?.chain).toEqual([{ kind: 'default', value: null }]);
    expect(network?.moved).toBe(false);

    await run({ command: 'apply', cwd: box.root });
    // Артефакт перегенерирован целиком: слой пресета не развернулся вовсе.
    expect(box.read(dest)).not.toContain('--network=');
    expect(box.read(dest)).not.toContain('mounts');
  });
});

describe('переход: обвес обновился, дефолт поднялся', () => {
  const BUMPED = `
export function repoName(ctx) { return ctx.repo.name; }
export function devboxName(ctx) { return \`\${ctx.repo.name}-devbox\`; }
export function latestStableNode() { return '24'; }
`;

  it('движение названо ДО применения, и артефакт догоняет эталон', async () => {
    const { box, dest } = ownable();
    await run({ command: 'apply', cwd: box.root });
    expect(box.read(dest)).toContain('typescript-node:22');

    box.updateResolvers(BUMPED);

    // Сначала ПЛАН: движение обязано быть названо до того, как что-то поедет.
    const plan = await run({ command: 'plan', cwd: box.root });
    const runtime = plan.settings.find(
      (setting) => setting.key === 'runtimeVersion',
    );
    expect(runtime?.value).toBe('24');
    expect(runtime?.ours).toBe(true);
    expect(plan.plan?.steps[0].reason).toBe('diverged');
    // Названо — и не применено: команда `plan` дерева не трогает.
    expect(box.read(dest)).toContain('typescript-node:22');

    await run({ command: 'apply', cwd: box.root });
    expect(box.read(dest)).toContain('typescript-node:24');
  });

  it('заполненное пользователем переживает обновление обвеса', async () => {
    consumer = installDevbox({
      config: {
        formVersion: 1,
        sources: [
          {
            use: DEVBOX_PACKAGE,
            presets: ['omnifield'],
            settings: { runtimeVersion: '20' },
          },
        ],
      },
    });
    const dest = makeArtifactOwnable(consumer);
    await run({ command: 'apply', cwd: consumer.root });

    consumer.updateResolvers(BUMPED);
    await run({ command: 'apply', cwd: consumer.root });

    // Дефолт под ним уехал на 24 — значение осталось: подниматься неоткуда,
    // движок в конфиг пользователя не пишет.
    expect(consumer.read(dest)).toContain('typescript-node:20');
  });
});

describe('переход: артефакт правили руками', () => {
  it('перегенерируется целиком — правка не переживает, и это названо', async () => {
    const { box, dest } = ownable();
    await run({ command: 'apply', cwd: box.root });

    const landed = box.read(dest) as string;
    box.write(dest, `${landed}\n// правка руками\n`);

    const plan = await run({ command: 'plan', cwd: box.root });
    const [step] = plan.plan?.steps ?? [];

    expect(step.reason).toBe('diverged');
    // Потери названы ДО применения: прежнее содержимое едет в плане данными.
    expect(step.previous).toContain('правка руками');

    await run({ command: 'apply', cwd: box.root });
    expect(box.read(dest)).toBe(landed);
  });
});

describe('переход: запись ушла из раскладки', () => {
  it('артефакт снимается с ДИСКА, а не только из виртуального дерева', async () => {
    const { box, dest } = ownable();
    await run({ command: 'apply', cwd: box.root });
    expect(box.exists(dest)).toBe(true);

    box.updateSource((block) => {
      const layout = block['layout'] as { src: string }[];
      block['layout'] = layout.filter((item) => !item.src.endsWith('.ejs'));
    });

    const result = await run({ command: 'apply', cwd: box.root });

    expect(result.plan?.steps[0].reason).toBe('orphan');
    expect(result.writes).toContainEqual({ path: dest, kind: 'DELETE' });
    // Сброс на ФС обязан уносить удаления так же, как записи.
    expect(box.exists(dest)).toBe(false);
    expect(box.exists(LOCK)).toBe(true);
  });
});

describe('переход: на месте артефакта лежит чужой файл', () => {
  it('отказ вместо тихой перезаписи — и на диске остаётся чужое', async () => {
    const { box, dest } = ownable();
    box.write(dest, '// чужой файл\n{"name":"не наш"}\n');

    const result = await run({ command: 'apply', cwd: box.root });

    expect(result.status).toBe('blocked');
    expect(result.plan?.conflicts[0].kind).toBe('foreign-dest');
    expect(box.read(dest)).toContain('не наш');
    // Применение целиком либо никак: соседний артефакт тоже не лёг.
    expect(box.exists(LOCK)).toBe(false);
  });

  it('подтверждение снимает отказ ПОИМЁННО и не масштабируется само', async () => {
    const { box, dest } = ownable();
    box.write(dest, '// чужой файл\n{"name":"не наш"}\n');
    box.write(LOCK, '{"features":{}}\n');

    // Подтверждаем ОДИН артефакт из двух чужих.
    const result = await run({
      command: 'apply',
      cwd: box.root,
      confirm: [dest],
    });

    // Согласие на один не стало согласием на соседний — план всё ещё блокирован.
    expect(result.status).toBe('blocked');
    expect(result.plan?.conflicts.map((item) => item.dest)).toEqual([LOCK]);
    expect(box.read(dest)).toContain('не наш');

    // Подтверждаем оба — и оба берутся во владение как усыновлённые.
    const both = await run({
      command: 'apply',
      cwd: box.root,
      confirm: [dest, LOCK],
    });
    expect(both.status).toBe('applied');
    expect(both.plan?.steps.every((step) => step.reason === 'adopted')).toBe(
      true,
    );
    expect(readOwnership(treeless(box, dest), dest)).not.toBeNull();
  });
});

/** Мини-дерево над реальной ФС: читать владение с диска нечем, а надо. */
function treeless(box: Consumer, dest: string) {
  return {
    exists: (path: string) => box.exists(path),
    read: (path: string) => box.read(path),
  } as unknown as Parameters<typeof readOwnership>[0];
}

function withoutLine(text: string, line: number): string {
  const lines = text.split('\n');
  lines.splice(line - 1, 1);
  return lines.join('\n');
}
