import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import type { Declaration, LayoutEntry } from './declaration.js';
import { computePlan, describePlan, isApplicable } from './plan.js';
import { applyPlan } from './apply.js';
import { MANIFEST_PATH, hashContent } from './manifest.js';
import * as api from '../index.js';
import {
  CONTENT_ROOT,
  SOURCE_ID,
  createWorkspace,
  manifestOf,
  redeclare,
} from './workspace.fixture.js';

const WORKFLOW = '.github/workflows/build.yml';

const exactEntry: LayoutEntry = { src: 'ci/build.yml', dest: WORKFLOW };
const jsonEntry: LayoutEntry = { src: 'ts/tsconfig.json', dest: 'tsconfig.json' };
const ignoreEntry: LayoutEntry = { src: 'repo/gitignore', dest: '.gitignore' };
const docEntry: LayoutEntry = {
  src: 'docs/CONTRIBUTING.md',
  dest: 'CONTRIBUTING.md',
};

const SOURCES = {
  'ci/build.yml': 'name: build\njobs: {}\n',
  'ts/tsconfig.json': '{ "compilerOptions": { "strict": true } }',
  'repo/gitignore': 'node_modules\ndist\n',
  'docs/CONTRIBUTING.md': '# как участвовать\n',
};

describe('computePlan — чего не хватает', () => {
  it('объявленный, но отсутствующий артефакт даёт шаг создания', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.status).toBe('pending');
    expect(plan.steps).toHaveLength(1);
    expect(plan.steps[0]).toMatchObject({
      kind: 'create',
      dest: WORKFLOW,
      reason: 'missing',
      previous: null,
    });
    expect(plan.steps[0].content).toContain('name: build');
  });

  it('план не трогает дерево — он данные, а не побочка', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });

    computePlan({ tree, declaration });

    expect(tree.exists(WORKFLOW)).toBe(false);
  });

  it('план читается человеком до применения', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });

    const text = describePlan(computePlan({ tree, declaration }));

    expect(text).toContain('create');
    expect(text).toContain(WORKFLOW);
  });
});

describe('computePlan — что разошлось', () => {
  it('правка в нашем артефакте даёт шаг обновления с прежним содержимым', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));

    const materialized = tree.read(WORKFLOW, 'utf-8') as string;
    tree.write(
      WORKFLOW,
      materialized.replace('jobs: {}', 'jobs: { local: {} }'),
    );

    const plan = computePlan({ tree, declaration });

    expect(plan.steps).toHaveLength(1);
    expect(plan.steps[0]).toMatchObject({ kind: 'update', reason: 'diverged' });
    expect(plan.steps[0].previous).toContain('local');
    expect(plan.steps[0].content).not.toContain('local');
  });

  it('план НАЗЫВАЕТ потери: правка видна в previous до применения', () => {
    // «Затирание само по себе не дефект. Дефектом было молчание» (`kb:BASER2-2`).
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));
    tree.write(
      WORKFLOW,
      `${tree.read(WORKFLOW, 'utf-8') as string}# моя правка\n`,
    );

    const plan = computePlan({ tree, declaration });

    expect(plan.steps[0].previous).toContain('# моя правка');
    expect(plan.steps[0].content).not.toContain('# моя правка');
  });
});

/**
 * ГЛАВНЫЙ ИНВАРИАНТ ЗОНЫ ПОСЛЕ A1 (`tasker:BASER2-3`, `kb:BASER2-2`).
 *
 * Движок НИКОГДА не сводит исходную, пользовательскую и новую версию файла —
 * ни в каком виде, ни под каким флагом. Результат материализации при любом
 * входе равен шаблону целиком; ничего от прежнего содержимого артефакта в него
 * не попадает.
 */
describe('сведения версий не происходит ни при каком входе', () => {
  const template = 'node_modules\ndist\n';

  /** Все входы, которые в модели B дали бы сведение версий. */
  const inputs: ReadonlyArray<readonly [string, string]> = [
    ['пользователь дописал строку', 'node_modules\ndist\ncoverage\n'],
    ['пользователь удалил строку', 'node_modules\n'],
    ['пользователь переписал файл целиком', 'совсем другое содержимое\n'],
    ['пользователь оставил пустой файл', ''],
    ['файл, помеченный движком прошлой модели', '# ~~ Generated by … ~~\nмой вклад\n'],
  ];

  it.each(inputs)('%s → артефакт равен шаблону целиком', (_case, existing) => {
    const { tree, declaration } = createWorkspace({
      layout: [ignoreEntry],
      sources: SOURCES,
      existing: { '.gitignore': existing },
    });

    const plan = computePlan({
      tree,
      declaration,
      confirm: ['.gitignore'],
    });
    applyPlan(tree, plan);

    // Байт в байт: движок содержимое не трогает вовсе, поэтому и снимать с
    // результата нечего — ни маркера, ни переслоенного JSON.
    expect(tree.read('.gitignore', 'utf-8')).toBe(template);
  });

  it('повторный прогон поверх правки снова даёт шаблон, а не накопление', () => {
    const { tree, declaration } = createWorkspace({
      layout: [ignoreEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));

    for (const patch of ['coverage\n', 'tmp\n', 'моё\n']) {
      tree.write(
        '.gitignore',
        `${tree.read('.gitignore', 'utf-8') as string}${patch}`,
      );
      applyPlan(tree, computePlan({ tree, declaration }));
      expect(tree.read('.gitignore', 'utf-8')).toBe(template);
    }
  });

  it('сводить нечем: у движка нет ни режимов, ни порта базы, ни класса владения', () => {
    // Инвариант держится ОТСУТСТВИЕМ механизма, а не поведением по умолчанию:
    // пока в публичной поверхности есть шов режимов или порт базы, «сведения не
    // происходит» — это договорённость, а не свойство движка.
    for (const removed of [
      'MATERIALIZE_MODES',
      'isMaterializeMode',
      'EMPTY_BASELINE',
      'createStrategyRegistry',
      'toStrategyRegistry',
      'StrategyRegistryError',
    ]) {
      expect(Object.keys(api)).not.toContain(removed);
    }
  });

  it('режим в записи раскладки ни на что не влияет — интерпретировать его некому', () => {
    // Отвергает `mode` разбор формы (зона контрактов), а движок про режимы не
    // знает вовсе: запись с посторонним полем даёт ровно тот же план, что и без
    // него. Проверяется рантаймом, потому что типом такое не поймать — поле
    // приходит из JSON, а не из кода.
    const withMode = createWorkspace({
      layout: [{ src: 'ci/build.yml', dest: WORKFLOW, mode: 'merge' } as never],
      sources: SOURCES,
    });
    const without = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });

    expect(computePlan(withMode).steps).toEqual(computePlan(without).steps);
  });
});

/**
 * И1.5 (`tasker:BASER2-23`). Движок ничего не читает сам: настоящая декларация
 * размазана по объявлению обвеса и конфигу потребителя, и склеивает их дверь.
 * Движку подают готовую структуру — а он за это отвечает своей границей.
 */
describe('движок принимает готовую структуру', () => {
  it('планирует и применяет без единого файла-манифеста в дереве', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry, ignoreEntry],
      sources: SOURCES,
    });
    // ни манифеста обвеса, ни конфига потребителя в дереве нет
    tree.delete('package.json');

    const plan = computePlan({ tree, declaration });
    applyPlan(tree, plan);

    expect(plan.status).toBe('pending');
    expect(tree.read(WORKFLOW, 'utf-8')).toContain('name: build');
    expect(computePlan({ tree, declaration }).status).toBe('converged');
  });

  it('чтения декларации в публичной поверхности нет', () => {
    // Знание про манифест — это знание двери, а не станка. Пока экспорт жив,
    // «движок не читает файл» остаётся договорённостью, а не свойством.
    for (const removed of [
      'readDeclaration',
      'parseDeclaration',
      'DECLARATION_BLOCK',
      'DEFAULT_DECLARATION_PATH',
    ]) {
      expect(Object.keys(api)).not.toContain(removed);
    }
  });

  it('структура не той формы отвергается внятно, а не TypeError из недр', () => {
    const { tree } = createWorkspace({ layout: [], sources: SOURCES });
    const cases: ReadonlyArray<readonly [string, unknown]> = [
      ['layout отсутствует', { source: { id: 'x/y', contentRoot: 'c' } }],
      ['layout не массив', { source: { id: 'x/y', contentRoot: 'c' }, layout: {} }],
      ['source отсутствует', { layout: [] }],
      ['contentRoot отсутствует', { source: { id: 'x/y' }, layout: [] }],
    ];

    for (const [name, declaration] of cases) {
      expect(() =>
        computePlan({ tree, declaration: declaration as never }),
      ).toThrow(api.DeclarationError);
      expect(() =>
        computePlan({ tree, declaration: declaration as never }),
        name,
      ).toThrow(/движку подана структура не той формы/);
    }
  });

  it('кривая ЗАПИСЬ раскладки не роняет план — отказ адресный', () => {
    // Форму записей проверяет дверь, но одна кривая запись не имеет права
    // уносить прогон: соседние планируются как обычно (тот же класс, что Д14).
    const { tree, declaration } = createWorkspace({
      layout: [{} as never, exactEntry],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.status).toBe('blocked');
    expect(plan.conflicts.map((conflict) => conflict.kind)).toEqual([
      'invalid-path',
    ]);
    expect(plan.steps.map((step) => step.dest)).toEqual([WORKFLOW]);
  });

  it('корень содержимого не может быть корнем дерева', () => {
    // Иначе защита «движок не пишет в собственный источник» отваливается:
    // `isInside` от пустого корня ложна, и шаблон становится законной целью —
    // прогон затирает файл, из которого сам же читает.
    for (const contentRoot of ['.', '', '/', './']) {
      const { tree, declaration } = createWorkspace({
        contentRoot,
        layout: [{ src: 'tpl/a.yml', dest: 'tpl/a.yml' }],
        sources: { 'tpl/a.yml': 'v: 1\n' },
      });

      expect(() => computePlan({ tree, declaration })).toThrow(
        api.DeclarationError,
      );
      expect(() => computePlan({ tree, declaration })).toThrow(
        /корень содержимого/,
      );
    }
  });

  it('файловой системы движок не касается: работа идёт только с деревом', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });

    applyPlan(tree, computePlan({ tree, declaration }));

    // Артефакт лежит в дереве и НЕ появился на диске: за сброс отвечает дверь.
    expect(tree.exists(WORKFLOW)).toBe(true);
    expect(existsSync(join(process.cwd(), WORKFLOW))).toBe(false);
  });
});

/**
 * A2 (`tasker:BASER2-4`). Служебная запись живёт СБОКУ, и из неё выводится
 * владение. Здесь проверяется то, ради чего переезд затевался: запись не
 * умеет соврать так, как врала наклейка внутри файла.
 */
describe('владение выводится из манифеста, а не из содержимого', () => {
  it('запись несёт путь, шаблон, обвес и хеш положенного', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });

    applyPlan(tree, computePlan({ tree, declaration }));

    expect(manifestOf(tree)).toEqual([
      {
        dest: WORKFLOW,
        src: 'ci/build.yml',
        source: SOURCE_ID,
        hash: hashContent(SOURCES['ci/build.yml']),
      },
    ]);
  });

  it('манифест лежит СБОКУ: в артефакте нет ни байта служебного', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });

    applyPlan(tree, computePlan({ tree, declaration }));

    expect(tree.read(WORKFLOW, 'utf-8')).toBe(SOURCES['ci/build.yml']);
    expect(tree.exists(MANIFEST_PATH)).toBe(true);
  });

  it('план называет манифест данными — до применения', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.manifestPath).toBe(MANIFEST_PATH);
    expect(plan.manifest.map((record) => record.dest)).toEqual([WORKFLOW]);
    // `plan` дерева не трогает — записи ещё нет.
    expect(tree.exists(MANIFEST_PATH)).toBe(false);
  });

  it('манифест не может быть целью раскладки: иначе прогон не сходится никогда', () => {
    // Найдено зондом: движок кладёт артефакт, а следом перезаписывает его же
    // служебной записью — и каждый следующий прогон снова видит расхождение.
    // Бесконечная работа, которая при этом рапортует «применено».
    const { tree, declaration } = createWorkspace({
      layout: [{ src: 'ci/build.yml', dest: MANIFEST_PATH }],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.status).toBe('blocked');
    expect(plan.conflicts[0]).toMatchObject({
      kind: 'dest-is-manifest',
      dest: MANIFEST_PATH,
      detail: { manifestPath: MANIFEST_PATH },
    });
    expect(plan.steps).toEqual([]);
  });

  it('битый манифест — отказ, а не «считаем, что записей нет»', () => {
    // Подменить нечитаемый манифест пустым значило бы объявить все свои
    // артефакты чужими: прогон превратился бы в отказ по каждому dest либо, под
    // подтверждением, в перезапись поверх непонятного состояния.
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));
    tree.write(MANIFEST_PATH, '{ это не json');

    expect(() => computePlan({ tree, declaration })).toThrow(api.ManifestError);
    expect(() => computePlan({ tree, declaration })).toThrow(
      /не разбирается как JSON/,
    );
  });

  it('манифест чужой версии — отказ, а не догадка о форме', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });
    tree.write(
      MANIFEST_PATH,
      `${JSON.stringify({ version: 99, artifacts: [] })}\n`,
    );

    expect(() => computePlan({ tree, declaration })).toThrow(api.ManifestError);
  });

  it('манифест пустеет — файл снимается, а не остаётся огрызком', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));

    applyPlan(
      tree,
      computePlan({ tree, declaration: redeclare(declaration, []) }),
    );

    expect(tree.exists(MANIFEST_PATH)).toBe(false);
    expect(tree.exists(WORKFLOW)).toBe(false);
  });

  it('порядок записей байтовый — файл лежит в git и не имеет права плавать', () => {
    const names = ['b.yml', 'A.yml', '_c.yml'];
    const { tree, declaration } = createWorkspace({
      layout: names.map((dest) => ({ src: 'ci/build.yml', dest })),
      sources: SOURCES,
    });

    applyPlan(tree, computePlan({ tree, declaration }));

    expect(manifestOf(tree).map((record) => record.dest)).toEqual(
      [...names].sort((left, right) => (left < right ? -1 : 1)),
    );
  });
});

/**
 * ИНВАРИАНТ Д10 (`tasker:BASER2-16`), внесённый явно.
 *
 * Если запись не утверждает ровно то, что объявляет декларация СЕЙЧАС,
 * приведение записи обязательно — независимо от того, совпало содержимое или
 * нет. Отсутствие записи — частный случай «не утверждает».
 *
 * В прошлой модели ровно здесь движок молчал: решение «содержимое уже целевое»
 * пропускало шаг ВМЕСТЕ с приведением служебного состояния, и устаревшая
 * претензия доживала до снятия не того файла.
 */
describe('запись обязана утверждать объявленное сейчас', () => {
  // Смена ОБВЕСА сюда не входит: артефакт, числящийся за другим поставщиком, —
  // это столкновение двух инструментов, а не устаревшая запись. Его исход —
  // отказ `cross-source-dest` (`kb:BASER2-6`), и он проверяется в разделе про
  // владение по каждому обвесу отдельно.
  it('сменился объявленный шаблон при том же содержимом → шаг record, файл не тронут', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: { ...SOURCES, 'ci/build-2.yml': SOURCES['ci/build.yml'] },
    });
    applyPlan(tree, computePlan({ tree, declaration }));
    const landed = tree.read(WORKFLOW, 'utf-8');

    const next = redeclare(declaration, [
      { src: 'ci/build-2.yml', dest: WORKFLOW },
    ]);
    const plan = computePlan({ tree, declaration: next });

    expect(plan.status).toBe('pending');
    expect(plan.steps[0]).toMatchObject({
      kind: 'record',
      dest: WORKFLOW,
      reason: 'reclaimed',
      content: null,
    });

    applyPlan(tree, plan);
    // Содержимое артефакта не тронуто — менялась только запись.
    expect(tree.read(WORKFLOW, 'utf-8')).toBe(landed);
    expect(computePlan({ tree, declaration: next }).status).toBe('converged');
  });

  it('устаревшая запись не доживает до снятия не того файла', () => {
    // Сценарий, на котором прошлая модель теряла файл: объявление сменилось,
    // содержимое совпало, шага не было — и следующее снятие записи уносило
    // артефакт по устаревшей претензии.
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: { ...SOURCES, 'ci/build-2.yml': SOURCES['ci/build.yml'] },
    });
    applyPlan(tree, computePlan({ tree, declaration }));

    const next = redeclare(declaration, [
      { src: 'ci/build-2.yml', dest: WORKFLOW },
    ]);
    applyPlan(tree, computePlan({ tree, declaration: next }));

    expect(manifestOf(tree)).toEqual([
      {
        dest: WORKFLOW,
        src: 'ci/build-2.yml',
        source: SOURCE_ID,
        hash: hashContent(SOURCES['ci/build.yml']),
      },
    ]);
  });

  it('правка, случайно совпавшая с новым шаблоном, приводит запись', () => {
    // Хеш записи устарел, а содержимое уже целевое. Без приведения записи
    // каждый следующий прогон видел бы расхождение и писал бы одно и то же.
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));

    tree.write(`${CONTENT_ROOT}/ci/build.yml`, 'name: следующая версия\n');
    tree.write(WORKFLOW, 'name: следующая версия\n'); // пользователь угадал

    const plan = computePlan({ tree, declaration });

    expect(plan.steps[0]).toMatchObject({ kind: 'record', reason: 'reclaimed' });

    applyPlan(tree, plan);
    expect(computePlan({ tree, declaration }).status).toBe('converged');
  });

  it('подделанный хеш в манифесте приводится к правде', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
      manifest: [
        {
          dest: WORKFLOW,
          src: 'ci/build.yml',
          source: SOURCE_ID,
          hash: hashContent('вообще не то'),
        },
      ],
      existing: { [WORKFLOW]: SOURCES['ci/build.yml'] },
    });

    const plan = computePlan({ tree, declaration });
    applyPlan(tree, plan);

    expect(plan.steps[0]).toMatchObject({ kind: 'record', reason: 'reclaimed' });
    expect(manifestOf(tree)[0].hash).toBe(hashContent(SOURCES['ci/build.yml']));
  });
});

/**
 * И1.6 (`tasker:BASER2-24`). Шаблоны физически лежат в установленном пакете, то
 * есть могут быть ВНЕ дерева потребителя. Движок адресует источник
 * репо-относительным путём и им же защищается от записи в собственный
 * источник — значит случай «источника в этом дереве нет» он обязан назвать сам,
 * а не вырождаться в защиту, которой не за что зацепиться.
 */
describe('источник вне дерева назван, а не вырожден', () => {
  it('contentRoot: null — отказ с машинным кодом', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });
    const outside: Declaration = {
      ...declaration,
      source: { ...declaration.source, contentRoot: null },
    };

    expect(() => computePlan({ tree, declaration: outside })).toThrow(
      api.SourceOutsideTreeError,
    );
    try {
      computePlan({ tree, declaration: outside });
    } catch (error) {
      expect((error as api.BaserMaterializeError).code).toBe(
        'source-outside-tree',
      );
      // Адрес события — обвес: чинится это установкой обвеса в репозиторий.
      expect((error as Error).message).toContain(SOURCE_ID);
    }
  });

  it('источник внутри дерева — защита работает в полную силу, как раньше', () => {
    const { tree, declaration } = createWorkspace({
      layout: [{ src: 'ci/build.yml', dest: `${CONTENT_ROOT}/ci/build.yml` }],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.conflicts[0]).toMatchObject({
      kind: 'dest-in-content-root',
      detail: { contentRoot: CONTENT_ROOT },
    });
  });

  it('у каждого отказа движка есть машинный код', () => {
    // Дверь склеивает отказы формы, движка и свои в один список и ветвится по
    // кодам. Пока кода нет, она держит вторую правду о чужом событии.
    const { tree } = createWorkspace({ layout: [], sources: SOURCES });

    try {
      computePlan({ tree, declaration: { layout: [] } as never });
    } catch (error) {
      expect((error as api.BaserMaterializeError).code).toBe(
        'declaration-invalid',
      );
    }
  });
});

describe('идемпотентность (§1 контракта)', () => {
  it('прогон на выходе предыдущего прогона даёт ПУСТОЙ план', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry, jsonEntry, ignoreEntry, docEntry],
      sources: SOURCES,
    });

    const first = computePlan({ tree, declaration });
    applyPlan(tree, first);
    const second = computePlan({ tree, declaration });

    expect(first.status).toBe('pending');
    expect(second.status).toBe('converged');
    expect(second.steps).toEqual([]);
    expect(second.conflicts).toEqual([]);
  });

  it('третий прогон тоже пуст — сходимость устойчива', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry, jsonEntry, ignoreEntry, docEntry],
      sources: SOURCES,
    });

    applyPlan(tree, computePlan({ tree, declaration }));
    applyPlan(tree, computePlan({ tree, declaration }));

    expect(computePlan({ tree, declaration }).status).toBe('converged');
  });
});

describe('сироты (§3 контракта)', () => {
  it('запись убрана из frame → артефакт движка снимается', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));
    expect(tree.exists(WORKFLOW)).toBe(true);

    const plan = computePlan({ tree, declaration: redeclare(declaration, []) });

    expect(plan.steps).toHaveLength(1);
    expect(plan.steps[0]).toMatchObject({
      kind: 'delete',
      dest: WORKFLOW,
      reason: 'orphan',
    });

    applyPlan(tree, plan);
    expect(tree.exists(WORKFLOW)).toBe(false);
  });

  it('осиротевший артефакт снимается целиком — развилки по классу владения нет', () => {
    // Раньше `shared`/`product` оставляли файл продукту. Пользовательских
    // файлов у движка больше нет: то, что должно пережить снятие записи, —
    // форкнутый источник, а форк живёт снаружи движка (`kb:BASER2-2`).
    const { tree, declaration } = createWorkspace({
      layout: [ignoreEntry, docEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));

    const plan = computePlan({ tree, declaration: redeclare(declaration, []) });

    expect(plan.steps.map((step) => [step.kind, step.dest])).toEqual([
      ['delete', '.gitignore'],
      ['delete', 'CONTRIBUTING.md'],
    ]);

    applyPlan(tree, plan);
    expect(tree.exists('.gitignore')).toBe(false);
    expect(tree.exists('CONTRIBUTING.md')).toBe(false);
  });

  it('чужой файл сиротой не считается — он не наш', () => {
    const { tree, declaration } = createWorkspace({
      layout: [],
      sources: SOURCES,
      existing: { '.gitignore': 'написано человеком\n' },
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.status).toBe('converged');
    expect(tree.read('.gitignore', 'utf-8')).toBe('написано человеком\n');
  });

  it('снятие сироты доводит дерево до пустого плана', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));

    const empty = redeclare(declaration, []);
    applyPlan(tree, computePlan({ tree, declaration: empty }));

    expect(computePlan({ tree, declaration: empty }).status).toBe('converged');
  });
});

describe('конфликт владения (§4 контракта)', () => {
  it('чужой файл не перезаписывается молча — отказ с внятным сообщением', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
      existing: { [WORKFLOW]: 'name: написано руками\n' },
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.steps).toEqual([]);
    expect(plan.status).toBe('blocked');
    expect(plan.conflicts[0]).toMatchObject({
      kind: 'foreign-dest',
      dest: WORKFLOW,
      detail: { resolution: 'confirm' },
    });
    expect(plan.conflicts[0].message).toContain('конфликт владения');
    expect(tree.read(WORKFLOW, 'utf-8')).toBe('name: написано руками\n');
  });

  it('перезапись возможна только поимённым подтверждением', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
      existing: { [WORKFLOW]: 'name: написано руками\n' },
    });

    const plan = computePlan({ tree, declaration, confirm: [WORKFLOW] });

    expect(plan.status).toBe('pending');
    expect(plan.steps[0]).toMatchObject({ kind: 'update', reason: 'adopted' });
  });

  it('согласие не масштабируется само: соседний отказ остаётся в силе', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry, ignoreEntry],
      sources: SOURCES,
      existing: {
        [WORKFLOW]: 'name: написано руками\n',
        '.gitignore': 'моё\n',
      },
    });

    const plan = computePlan({ tree, declaration, confirm: [WORKFLOW] });

    expect(plan.status).toBe('blocked');
    expect(plan.conflicts.map((conflict) => conflict.dest)).toEqual([
      '.gitignore',
    ]);
  });

  it('подтверждение, которое не понадобилось, названо извещением', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });

    const plan = computePlan({
      tree,
      declaration,
      confirm: [WORKFLOW, 'нет/такого.yml'],
    });

    expect(
      plan.notices.map((notice) => [notice.dest, notice.detail.confirmation]),
    ).toEqual([
      [WORKFLOW, 'not-required'],
      ['нет/такого.yml', 'not-declared'],
    ]);
  });

  it('два объявления одного dest — отказ, а не «последний победил»', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry, { ...exactEntry, src: 'ci/other.yml' }],
      sources: { ...SOURCES, 'ci/other.yml': 'name: other\n' },
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.conflicts.map((conflict) => conflict.kind)).toEqual([
      'duplicate-dest',
    ]);
    expect(plan.steps).toEqual([]);
  });

  it.each([
    ['без синтаксиса комментария', 'LICENSE', 'MIT\n'],
    ['JSON без объекта в корне', 'list.json', '[1, 2]\n'],
    ['JSONC с комментариями', 'cfg.json', '{\n  // так можно\n  "a": 1\n}\n'],
    ['бинарь-подобный', 'logo.png', '\u0089PNG\r\n\u001a\n'],
  ])(
    'класс файла больше не условие владения: %s',
    (_case, name, content) => {
      // Раньше здесь стоял отказ `unmarkable-dest`: доказать владение было
      // нечем, потому что наклейку некуда поставить. Запись сбоку сняла условие
      // целиком — движок кладёт содержимое как есть и владеет по манифесту.
      const { tree, declaration } = createWorkspace({
        layout: [{ src: name, dest: name }],
        sources: { [name]: content },
      });

      const plan = computePlan({ tree, declaration });
      applyPlan(tree, plan);

      expect(plan.conflicts).toEqual([]);
      expect(tree.read(name, 'utf-8')).toBe(content);
      expect(manifestOf(tree)[0]).toMatchObject({ dest: name, src: name });
      expect(computePlan({ tree, declaration }).status).toBe('converged');
    },
  );

  it('отсутствующий шаблон называет полный путь', () => {
    const { tree, declaration } = createWorkspace({ layout: [exactEntry] });

    const plan = computePlan({ tree, declaration });

    expect(plan.conflicts[0]).toMatchObject({ kind: 'missing-source' });
    expect(plan.conflicts[0].message).toContain(`${CONTENT_ROOT}/ci/build.yml`);
  });
});

/**
 * «Нечего делать» и «сошлось» — разные состояния. Гейт вяжет exit-код к
 * сходимости, и зелёный гейт на нерешённом конфликте владения опаснее
 * отсутствующего.
 */
describe('сходимость отделена от пустоты', () => {
  it('план без шагов, но с конфликтом, сходимости НЕ означает', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
      existing: { [WORKFLOW]: 'name: написано руками\n' },
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.steps).toEqual([]);
    expect(plan.conflicts).toHaveLength(1);
    expect(plan.status).toBe('blocked');
    expect(isApplicable(plan)).toBe(false);
  });

  it('признака «в плане нет шагов» в схеме нет — сходимость нельзя получить случайно', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
      existing: { [WORKFLOW]: 'name: написано руками\n' },
    });

    const plan = computePlan({ tree, declaration });

    expect(Object.keys(plan)).not.toContain('empty');
    expect(Object.keys(plan)).not.toContain('applicable');
  });

  it('сошлось — это отсутствие и шагов, и конфликтов', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));

    const plan = computePlan({ tree, declaration });

    expect(plan.status).toBe('converged');
    expect(isApplicable(plan)).toBe(true);
  });
});

/**
 * «Файл разошёлся с шаблоном» и «файл впервые взят под управление» — разные
 * события, и гейт обязан показывать их по-разному.
 */
describe('причина шага обязана быть правдой', () => {
  it('чужой файл под подтверждением берётся с причиной adopted', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
      existing: { [WORKFLOW]: 'name: написано руками\n' },
    });

    const plan = computePlan({ tree, declaration, confirm: [WORKFLOW] });

    expect(plan.steps[0]).toMatchObject({ reason: 'adopted' });
  });

  it('расхождение нашего артефакта остаётся diverged', () => {
    const { tree, declaration } = createWorkspace({
      layout: [ignoreEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));
    tree.write(
      '.gitignore',
      (tree.read('.gitignore', 'utf-8') as string).replace('dist', 'build'),
    );

    const plan = computePlan({ tree, declaration });

    expect(plan.steps[0]).toMatchObject({ reason: 'diverged' });
  });

  it('смена объявленного src приводит служебную запись — причина reclaimed', () => {
    // Запись обязана утверждать ровно то, что объявляет декларация СЕЙЧАС, —
    // даже когда содержимое совпало и шага по телу не требуется.
    const { tree, declaration } = createWorkspace({
      layout: [ignoreEntry],
      sources: { ...SOURCES, 'repo/gitignore-2': SOURCES['repo/gitignore'] },
    });
    applyPlan(tree, computePlan({ tree, declaration }));
    expect(manifestOf(tree)).toEqual([
      {
        dest: '.gitignore',
        src: 'repo/gitignore',
        source: SOURCE_ID,
        hash: hashContent(SOURCES['repo/gitignore']),
      },
    ]);

    const next = redeclare(declaration, [
      { src: 'repo/gitignore-2', dest: '.gitignore' },
    ]);
    const plan = computePlan({ tree, declaration: next });

    // Содержимое ТО ЖЕ — шаг всё равно есть, и он про запись, а не про файл.
    expect(plan.steps[0]).toMatchObject({
      kind: 'record',
      reason: 'reclaimed',
      content: null,
    });

    const before = tree.read('.gitignore', 'utf-8');
    applyPlan(tree, plan);
    expect(tree.read('.gitignore', 'utf-8')).toBe(before);
    expect(manifestOf(tree)[0].src).toBe('repo/gitignore-2');
    expect(computePlan({ tree, declaration: next }).status).toBe('converged');
  });
});

/**
 * Приёмочный критерий: любую операцию можно вызвать программно и получить
 * полный результат ДАННЫМИ, ни разу не разобрав текст.
 */
describe('вывод машинночитаем в первую очередь', () => {
  it('каждая причина отказа доступна кодом и данными, а не только текстом', () => {
    const { tree, declaration } = createWorkspace({
      layout: [
        exactEntry,
        { ...exactEntry, src: 'ci/other.yml' },
        { src: 'ci/missing.yml', dest: 'ci/missing.yml' },
        { src: 'ci/build.yml', dest: `${CONTENT_ROOT}/ci/build.yml` },
      ],
      sources: { ...SOURCES, 'ci/other.yml': 'name: other\n' },
    });

    const plan = computePlan({ tree, declaration });
    const byKind = new Map(
      plan.conflicts.map((conflict) => [conflict.kind, conflict]),
    );

    expect(byKind.get('duplicate-dest')?.detail).toEqual({
      claimedBy: 'ci/build.yml',
    });
    expect(byKind.get('missing-source')?.detail).toEqual({
      sourcePath: `${CONTENT_ROOT}/ci/missing.yml`,
    });
    expect(byKind.get('dest-in-content-root')?.detail).toEqual({
      contentRoot: CONTENT_ROOT,
    });
  });

  it('план и отчёт переживают сериализацию: решение принимается без парсинга текста', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry, ignoreEntry, docEntry],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });
    const report = applyPlan(tree, plan);
    const wire = JSON.parse(JSON.stringify({ plan, report }));

    expect(wire.plan.schemaVersion).toBe(plan.schemaVersion);
    expect(wire.report.schemaVersion).toBe(plan.schemaVersion);
    expect(wire.plan.status).toBe('pending');
    expect(
      wire.plan.steps.map((step: { kind: string; reason: string }) => [
        step.kind,
        step.reason,
      ]),
    ).toEqual([
      ['create', 'missing'],
      ['create', 'missing'],
      ['create', 'missing'],
    ]);
    expect(wire.report.applied).toHaveLength(3);
    expect(wire.report.trace[0].name).toBe('apply.steps');
  });

  it('версия схемы вывода поднята: форма несовместима с прежней', () => {
    // 2 — снятие мерджа, 3 — словарь контракта, 4 — служебная запись уехала
    // из артефактов в манифест сбоку.
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });

    expect(computePlan({ tree, declaration }).schemaVersion).toBe(4);
  });

  it('трейсы — именованные спаны с длительностью и атрибутами', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    for (const span of plan.trace) {
      expect(typeof span.name).toBe('string');
      expect(typeof span.ms).toBe('number');
    }
    // Событие владения называет и весь манифест, и долю ЭТОГО обвеса: прогон
    // распоряжается только своей долей, и это обязано быть видно в телеметрии.
    expect(
      plan.trace.find((span) => span.name === 'plan.owned')?.detail,
    ).toEqual({ source: SOURCE_ID, records: 0, own: 0 });
  });
});

/**
 * Атомарность движка кончается на виртуальном дереве: сброс на реальную ФС
 * делает раннер, и его сбой происходит уже ВНЕ журнала отката. Поэтому всё,
 * что упадёт при записи на диск, обязано быть поймано ПЛАНОМ.
 */
describe('объявленное состояние обязано быть физически достижимым', () => {
  it('dest внутри пути другого dest — конфликт плана, а не сходимость', () => {
    const { tree, declaration } = createWorkspace({
      layout: [
        { src: 'ci/build.yml', dest: 'cfg.yml' },
        { src: 'ci/build.yml', dest: 'cfg.yml/inner.yml' },
      ],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.status).toBe('blocked');
    expect(plan.conflicts[0]).toMatchObject({
      kind: 'unreachable-dest',
      dest: 'cfg.yml/inner.yml',
      detail: { blockedBy: 'cfg.yml', collision: 'declared-dest' },
    });
    expect(plan.steps.map((step) => step.dest)).toEqual(['cfg.yml']);
  });

  it('порядок объявления не спасает: вложенный объявлен первым — отказ у внешнего', () => {
    const { tree, declaration } = createWorkspace({
      layout: [
        { src: 'ci/build.yml', dest: 'cfg.yml/inner.yml' },
        { src: 'ci/build.yml', dest: 'cfg.yml' },
      ],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.conflicts[0]).toMatchObject({
      kind: 'unreachable-dest',
      dest: 'cfg.yml',
      detail: { blockedBy: 'cfg.yml/inner.yml', collision: 'declared-dest' },
    });
  });

  it('родительский путь занят ЧУЖИМ файлом в дереве — конфликт плана', () => {
    const { tree, declaration } = createWorkspace({
      layout: [{ src: 'ci/build.yml', dest: 'cfg.yml/inner.yml' }],
      sources: SOURCES,
      existing: { 'cfg.yml': 'настройка: продукта\n' },
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.status).toBe('blocked');
    expect(plan.conflicts[0]).toMatchObject({
      kind: 'unreachable-dest',
      detail: { blockedBy: 'cfg.yml', collision: 'existing-file' },
    });
    expect(tree.read('cfg.yml', 'utf-8')).toBe('настройка: продукта\n');
  });

  it('коллизия отбивается ПО СУЩЕСТВУ, а не побочно правилом про маркер', () => {
    // `cfg` без расширения маркер нести не может, и раньше пара отбивалась
    // именно этим. Побочная защита отвалится, как только класс станет
    // размечаемым, — значит проверка обязана стоять по существу.
    const { tree, declaration } = createWorkspace({
      layout: [
        { src: 'ci/build.yml', dest: 'cfg' },
        { src: 'ci/build.yml', dest: 'cfg/inner.yml' },
      ],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    expect(
      plan.conflicts.find((conflict) => conflict.dest === 'cfg/inner.yml'),
    ).toMatchObject({
      kind: 'unreachable-dest',
      detail: { blockedBy: 'cfg', collision: 'declared-dest' },
    });
  });

  it('dest, чей путь занят ЧУЖИМ каталогом, — тот же класс недостижимости', () => {
    const { tree, declaration } = createWorkspace({
      layout: [{ src: 'ci/build.yml', dest: 'cfg' }],
      sources: SOURCES,
      existing: { 'cfg/inner.yml': 'настройка: продукта\n' },
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.status).toBe('blocked');
    expect(plan.conflicts[0]).toMatchObject({
      kind: 'unreachable-dest',
      dest: 'cfg',
      detail: { blockedBy: 'cfg', collision: 'existing-directory' },
    });
  });

  it('dest внутри contentRoot отбивается по существу, а не как чужой файл', () => {
    const { tree, declaration } = createWorkspace({
      layout: [{ src: 'ci/build.yml', dest: `${CONTENT_ROOT}/ci/build.yml` }],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.conflicts[0]).toMatchObject({
      kind: 'dest-in-content-root',
      detail: { contentRoot: CONTENT_ROOT },
    });
    expect(plan.steps).toEqual([]);
  });
});

/**
 * Д13 (`tasker:BASER2-16`). Асимметрия, найденная прогоном: ПИСАТЬ в собственный
 * источник движок отказывается (`dest-in-content-root`), а УДАЛЯТЬ оттуда —
 * штатным шагом, без конфликта, с `pending` в плане. В дефолтной раскладке было
 * замаскировано пропуском `node_modules`.
 */
describe('скан владения не трогает источник шаблонов', () => {
  it('помеченный файл внутри contentRoot сиротой не считается', () => {
    const { tree, declaration } = createWorkspace({
      contentRoot: 'content',
      layout: [{ src: 'a.yml', dest: 'a.yml' }],
      sources: { 'a.yml': 'name: a\n' },
    });
    applyPlan(tree, computePlan({ tree, declaration }));
    // в корне содержимого лежит артефакт с нашим маркером: шаблон-пример,
    // вложенный шаблон, копия артефакта — движку туда ходить нечем
    tree.write('content/sample.yml', tree.read('a.yml', 'utf-8') as string);

    const plan = computePlan({ tree, declaration });

    expect(plan.steps).toEqual([]);
    expect(plan.status).toBe('converged');
    expect(tree.exists('content/sample.yml')).toBe(true);
  });

  it('за пределами contentRoot сирота снимается по своей записи', () => {
    // Послабление узкое: оно про источник, а не про владение вообще.
    const { tree, declaration } = createWorkspace({
      contentRoot: 'content',
      layout: [
        { src: 'a.yml', dest: 'a.yml' },
        { src: 'a.yml', dest: 'elsewhere/sample.yml' },
      ],
      sources: { 'a.yml': 'name: a\n' },
    });
    applyPlan(tree, computePlan({ tree, declaration }));

    const plan = computePlan({
      tree,
      declaration: redeclare(declaration, [{ src: 'a.yml', dest: 'a.yml' }]),
    });

    expect(plan.steps.map((step) => [step.kind, step.dest])).toEqual([
      ['delete', 'elsewhere/sample.yml'],
    ]);
  });
});

/**
 * Д14 (`tasker:BASER2-16`), новая форма. Старая причина ушла вместе со
 * стратегией, но требование переживает выпил: **сбой на одной записи или одном
 * источнике не имеет права уносить план целиком.** Отказ обязан быть привязан к
 * конкретному `dest`, а не улетать `TypeError`'ом из недр движка — с многими
 * источниками (A5) битый шаблон одного провайдера не должен гасить
 * материализацию всех остальных.
 */
describe('сбой на одной записи не уносит план целиком', () => {
  const brokenSource = (broken: string, tree: import('@nx/devkit').Tree) => ({
    read: (src: string) => {
      if (src === broken) {
        throw new TypeError(`шаблон ${src} битый`);
      }
      return tree.read(`${CONTENT_ROOT}/${src}`, 'utf-8');
    },
    describe: (src: string) => `${CONTENT_ROOT}/${src}`,
  });

  it('сбой источника становится отказом по своему dest, а не броском наружу', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry, ignoreEntry],
      sources: SOURCES,
    });

    const plan = computePlan({
      tree,
      declaration,
      source: brokenSource('ci/build.yml', tree),
    });

    expect(plan.status).toBe('blocked');
    expect(plan.conflicts).toHaveLength(1);
    expect(plan.conflicts[0]).toMatchObject({
      kind: 'entry-failed',
      dest: WORKFLOW,
      src: 'ci/build.yml',
    });
    expect(plan.conflicts[0].detail.failure).toContain('шаблон ci/build.yml битый');
  });

  it('соседние записи планируются как обычно — падение одной их не гасит', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry, ignoreEntry, jsonEntry],
      sources: SOURCES,
    });

    const plan = computePlan({
      tree,
      declaration,
      source: brokenSource('ci/build.yml', tree),
    });

    expect(plan.steps.map((step) => step.dest)).toEqual([
      '.gitignore',
      'tsconfig.json',
    ]);
  });

  it('сбой дерева на артефакте тоже привязан к dest', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry, ignoreEntry],
      sources: SOURCES,
      existing: { [WORKFLOW]: 'чужой\n' },
    });
    const broken = new Proxy(tree, {
      get(target, property, receiver) {
        if (property === 'read') {
          return (path: string, encoding?: string): unknown => {
            if (path === WORKFLOW) {
              throw new TypeError('дерево не отдаёт артефакт');
            }
            return (target.read as (p: string, e?: string) => unknown)(
              path,
              encoding,
            );
          };
        }
        const value = Reflect.get(target, property, receiver);
        return typeof value === 'function' ? value.bind(target) : value;
      },
    });

    const plan = computePlan({ tree: broken, declaration });

    expect(plan.conflicts.map((conflict) => [conflict.kind, conflict.dest])).toEqual(
      [['entry-failed', WORKFLOW]],
    );
    expect(plan.steps.map((step) => step.dest)).toEqual(['.gitignore']);
  });

  it('план с отказом по сбою неприменим целиком', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry, ignoreEntry],
      sources: SOURCES,
    });

    const plan = computePlan({
      tree,
      declaration,
      source: brokenSource('ci/build.yml', tree),
    });

    expect(isApplicable(plan)).toBe(false);
    expect(tree.exists('.gitignore')).toBe(false);
  });
});

/**
 * Нит (`tasker:BASER2-16`). Схема вывода — контракт с пультом, и порядок в нём
 * не имеет права плавать между окружениями по ICU и локали процесса.
 * `localeCompare` даёт разный порядок при разной локали; сравнение байтовое —
 * одинаковый везде.
 */
describe('порядок машинного вывода детерминирован', () => {
  const named = ['B.yml', 'a.yml', '_x.yml', 'A.yml', 'Z.yml'];

  it('шаги упорядочены байтово, а не локале-зависимо', () => {
    const { tree, declaration } = createWorkspace({
      layout: named.map((dest, index) => ({ src: `s${index}.yml`, dest })),
      sources: Object.fromEntries(
        named.map((_dest, index) => [`s${index}.yml`, `v: ${index}\n`]),
      ),
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.steps.map((step) => step.dest)).toEqual(
      [...named].sort((left, right) => (left < right ? -1 : left > right ? 1 : 0)),
    );
  });

  it('конфликты и извещения упорядочены тем же сравнением', () => {
    const { tree, declaration } = createWorkspace({
      layout: named.map((dest, index) => ({ src: `s${index}.yml`, dest })),
      sources: Object.fromEntries(
        named.map((_dest, index) => [`s${index}.yml`, `v: ${index}\n`]),
      ),
      existing: Object.fromEntries(named.map((dest) => [dest, 'чужой\n'])),
    });

    const plan = computePlan({
      tree,
      declaration,
      confirm: named.map((dest) => `нет-${dest}`),
    });
    const byBytes = (values: readonly string[]) =>
      [...values].sort((left, right) =>
        left < right ? -1 : left > right ? 1 : 0,
      );

    expect(plan.conflicts.map((conflict) => conflict.dest)).toEqual(
      byBytes(named),
    );
    expect(plan.notices.map((notice) => notice.dest)).toEqual(
      byBytes(named.map((dest) => `нет-${dest}`)),
    );
  });

  it('порядок не зависит от локали процесса', () => {
    // Тот же вход, разное сравнение: локале-зависимая сортировка ставит
    // `_x.yml` и `a.yml` иначе, чем байтовая, — план обязан давать вторую.
    const locale = [...named].sort((left, right) => left.localeCompare(right));
    const bytes = [...named].sort((left, right) =>
      left < right ? -1 : left > right ? 1 : 0,
    );
    expect(locale).not.toEqual(bytes);

    const { tree, declaration } = createWorkspace({
      layout: named.map((dest, index) => ({ src: `s${index}.yml`, dest })),
      sources: Object.fromEntries(
        named.map((_dest, index) => [`s${index}.yml`, `v: ${index}\n`]),
      ),
    });

    expect(computePlan({ tree, declaration }).steps.map((s) => s.dest)).not.toEqual(
      locale,
    );
  });
});

/**
 * Сироты ищутся ПО ЗАПИСЯМ, а не сканом дерева. Слепых зон у такого поиска нет
 * по построению — вместе со сканом ушли и его пропуски, и извещение об охвате,
 * и целый класс дефектов: чужой файл, случайно похожий на наш, больше не
 * находится «нашим» никогда.
 */
describe('поиск сирот не ходит по дереву', () => {
  it('чужой файл, похожий на артефакт, сиротой не считается', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));
    // Копия нашего артефакта, положенная кем-то другим: записи о ней нет.
    tree.write('vendor/copy.yml', tree.read(WORKFLOW, 'utf-8') as string);

    const plan = computePlan({ tree, declaration });

    expect(plan.status).toBe('converged');
    expect(tree.exists('vendor/copy.yml')).toBe(true);
  });

  it('артефакт в любом каталоге снимается по записи, без охватов и пропусков', () => {
    const { tree, declaration } = createWorkspace({
      layout: [{ src: 'ci/build.yml', dest: 'node_modules/.cache/x.yml' }],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));

    const plan = computePlan({ tree, declaration: redeclare(declaration, []) });

    expect(plan.steps).toEqual([
      expect.objectContaining({
        kind: 'delete',
        dest: 'node_modules/.cache/x.yml',
        reason: 'orphan',
      }),
    ]);
  });

  it('извещения об охвате скана больше нет — как и самого скана', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.notices).toEqual([]);
    expect(Object.keys(api)).not.toContain('scanOwnership');
    expect(Object.keys(api)).not.toContain('DEFAULT_SCAN_IGNORE');
  });
});

describe('трейсы', () => {
  it('план несёт замеры этапов', () => {
    const { tree, declaration } = createWorkspace({
      layout: [exactEntry],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.trace.map((span) => span.name)).toEqual([
      'plan.manifest',
      'plan.owned',
      'plan.layout',
      'plan.orphans',
    ]);
    expect(
      plan.trace.find((span) => span.name === 'plan.layout')?.detail,
    ).toEqual({ entries: 1 });
  });
});
