import { describe, expect, it } from 'vitest';
import type { FrameEntry } from './declaration.js';
import { computePlan, describePlan, isApplicable } from './plan.js';
import { applyPlan } from './apply.js';
import { DEFAULT_SCAN_IGNORE, readOwnership } from './ownership.js';
import * as api from '../index.js';
import {
  CONTENT_ROOT,
  createWorkspace,
  redeclare,
} from './workspace.fixture.js';

const WORKFLOW = '.github/workflows/build.yml';

const exactEntry: FrameEntry = { src: 'ci/build.yml', dest: WORKFLOW };
const jsonEntry: FrameEntry = { src: 'ts/tsconfig.json', dest: 'tsconfig.json' };
const ignoreEntry: FrameEntry = { src: 'repo/gitignore', dest: '.gitignore' };
const docEntry: FrameEntry = {
  src: 'docs/CONTRIBUTING.md',
  dest: 'CONTRIBUTING.md',
};

const SOURCES = {
  'ci/build.yml': 'name: build\njobs: {}\n',
  'ts/tsconfig.json': '{ "compilerOptions": { "strict": true } }',
  'repo/gitignore': 'node_modules\ndist\n',
  'docs/CONTRIBUTING.md': '# как участвовать\n',
};

describe('computePlan — чего не хватает', () => {
  it('объявленный, но отсутствующий артефакт даёт шаг создания', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.status).toBe('pending');
    expect(plan.steps).toHaveLength(1);
    expect(plan.steps[0]).toMatchObject({
      kind: 'create',
      dest: WORKFLOW,
      reason: 'missing',
      previous: null,
    });
    expect(plan.steps[0].content).toContain('name: build');
  });

  it('план не трогает дерево — он данные, а не побочка', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
    });

    computePlan({ tree, declaration });

    expect(tree.exists(WORKFLOW)).toBe(false);
  });

  it('план читается человеком до применения', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
    });

    const text = describePlan(computePlan({ tree, declaration }));

    expect(text).toContain('create');
    expect(text).toContain(WORKFLOW);
  });
});

describe('computePlan — что разошлось', () => {
  it('правка в нашем артефакте даёт шаг обновления с прежним содержимым', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));

    const materialized = tree.read(WORKFLOW, 'utf-8') as string;
    tree.write(
      WORKFLOW,
      materialized.replace('jobs: {}', 'jobs: { local: {} }'),
    );

    const plan = computePlan({ tree, declaration });

    expect(plan.steps).toHaveLength(1);
    expect(plan.steps[0]).toMatchObject({ kind: 'update', reason: 'diverged' });
    expect(plan.steps[0].previous).toContain('local');
    expect(plan.steps[0].content).not.toContain('local');
  });

  it('план НАЗЫВАЕТ потери: правка видна в previous до применения', () => {
    // «Затирание само по себе не дефект. Дефектом было молчание» (`kb:BASER2-2`).
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));
    tree.write(
      WORKFLOW,
      `${tree.read(WORKFLOW, 'utf-8') as string}# моя правка\n`,
    );

    const plan = computePlan({ tree, declaration });

    expect(plan.steps[0].previous).toContain('# моя правка');
    expect(plan.steps[0].content).not.toContain('# моя правка');
  });
});

/**
 * ГЛАВНЫЙ ИНВАРИАНТ ЗОНЫ ПОСЛЕ A1 (`tasker:BASER2-3`, `kb:BASER2-2`).
 *
 * Движок НИКОГДА не сводит исходную, пользовательскую и новую версию файла —
 * ни в каком виде, ни под каким флагом. Результат материализации при любом
 * входе равен шаблону целиком; ничего от прежнего содержимого артефакта в него
 * не попадает.
 */
describe('сведения версий не происходит ни при каком входе', () => {
  const template = 'node_modules\ndist\n';

  /** Все входы, которые в модели B дали бы сведение версий. */
  const inputs: ReadonlyArray<readonly [string, string]> = [
    ['пользователь дописал строку', 'node_modules\ndist\ncoverage\n'],
    ['пользователь удалил строку', 'node_modules\n'],
    ['пользователь переписал файл целиком', 'совсем другое содержимое\n'],
    ['пользователь оставил пустой файл', ''],
    [
      'файл помечен движком ДО выпила (маркер с mode/own/version)',
      '# ~~ Generated by @omnifield/baser-materialize ~~ ручные правки не сохраняются — правь декларацию ~~ ' +
        '{"src":"repo/gitignore","mode":"merge","own":"shared","version":"1.4.0"}\n' +
        'node_modules\nмой вклад\n',
    ],
  ];

  it.each(inputs)('%s → артефакт равен шаблону целиком', (_case, existing) => {
    const { tree, declaration } = createWorkspace({
      frame: [ignoreEntry],
      sources: SOURCES,
      existing: { '.gitignore': existing },
    });

    const plan = computePlan({
      tree,
      declaration,
      confirm: ['.gitignore'],
    });
    applyPlan(tree, plan);

    const result = tree.read('.gitignore', 'utf-8') as string;
    const format = api.markerFormatFor('.gitignore');
    expect(format?.strip(result)).toBe(template);
    // ни одной строки прежнего содержимого, которой нет в шаблоне
    for (const line of existing.split('\n')) {
      if (line !== '' && !template.includes(line) && !line.startsWith('# ~~')) {
        expect(result).not.toContain(line);
      }
    }
  });

  it('повторный прогон поверх правки снова даёт шаблон, а не накопление', () => {
    const { tree, declaration } = createWorkspace({
      frame: [ignoreEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));

    for (const patch of ['coverage\n', 'tmp\n', 'моё\n']) {
      tree.write(
        '.gitignore',
        `${tree.read('.gitignore', 'utf-8') as string}${patch}`,
      );
      applyPlan(tree, computePlan({ tree, declaration }));
      expect(
        api.markerFormatFor('.gitignore')?.strip(
          tree.read('.gitignore', 'utf-8') as string,
        ),
      ).toBe(template);
    }
  });

  it('сводить нечем: у движка нет ни режимов, ни порта базы, ни класса владения', () => {
    // Инвариант держится ОТСУТСТВИЕМ механизма, а не поведением по умолчанию:
    // пока в публичной поверхности есть шов режимов или порт базы, «сведения не
    // происходит» — это договорённость, а не свойство движка.
    for (const removed of [
      'MATERIALIZE_MODES',
      'isMaterializeMode',
      'EMPTY_BASELINE',
      'createStrategyRegistry',
      'toStrategyRegistry',
      'StrategyRegistryError',
    ]) {
      expect(Object.keys(api)).not.toContain(removed);
    }
  });

  it('декларация не принимает mode ни в одном виде', () => {
    for (const mode of ['exact', 'merge', 'seed', 'что угодно']) {
      expect(() =>
        api.parseDeclaration(
          { contentRoot: 'content', frame: [{ src: 'a.yml', dest: 'b.yml', mode }] },
          'package.json',
        ),
      ).toThrow(api.DeclarationError);
    }
  });
});

describe('идемпотентность (§1 контракта)', () => {
  it('прогон на выходе предыдущего прогона даёт ПУСТОЙ план', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry, jsonEntry, ignoreEntry, docEntry],
      sources: SOURCES,
    });

    const first = computePlan({ tree, declaration });
    applyPlan(tree, first);
    const second = computePlan({ tree, declaration });

    expect(first.status).toBe('pending');
    expect(second.status).toBe('converged');
    expect(second.steps).toEqual([]);
    expect(second.conflicts).toEqual([]);
  });

  it('третий прогон тоже пуст — сходимость устойчива', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry, jsonEntry, ignoreEntry, docEntry],
      sources: SOURCES,
    });

    applyPlan(tree, computePlan({ tree, declaration }));
    applyPlan(tree, computePlan({ tree, declaration }));

    expect(computePlan({ tree, declaration }).status).toBe('converged');
  });
});

describe('сироты (§3 контракта)', () => {
  it('запись убрана из frame → артефакт движка снимается', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));
    expect(tree.exists(WORKFLOW)).toBe(true);

    const plan = computePlan({ tree, declaration: redeclare(tree, []) });

    expect(plan.steps).toHaveLength(1);
    expect(plan.steps[0]).toMatchObject({
      kind: 'delete',
      dest: WORKFLOW,
      reason: 'orphan',
    });

    applyPlan(tree, plan);
    expect(tree.exists(WORKFLOW)).toBe(false);
  });

  it('осиротевший артефакт снимается целиком — развилки по классу владения нет', () => {
    // Раньше `shared`/`product` оставляли файл продукту. Пользовательских
    // файлов у движка больше нет: то, что должно пережить снятие записи, —
    // форкнутый источник, а форк живёт снаружи движка (`kb:BASER2-2`).
    const { tree, declaration } = createWorkspace({
      frame: [ignoreEntry, docEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));

    const plan = computePlan({ tree, declaration: redeclare(tree, []) });

    expect(plan.steps.map((step) => [step.kind, step.dest])).toEqual([
      ['delete', '.gitignore'],
      ['delete', 'CONTRIBUTING.md'],
    ]);

    applyPlan(tree, plan);
    expect(tree.exists('.gitignore')).toBe(false);
    expect(tree.exists('CONTRIBUTING.md')).toBe(false);
  });

  it('чужой файл сиротой не считается — он не наш', () => {
    const { tree, declaration } = createWorkspace({
      frame: [],
      sources: SOURCES,
      existing: { '.gitignore': 'написано человеком\n' },
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.status).toBe('converged');
    expect(tree.read('.gitignore', 'utf-8')).toBe('написано человеком\n');
  });

  it('снятие сироты доводит дерево до пустого плана', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));

    const empty = redeclare(tree, []);
    applyPlan(tree, computePlan({ tree, declaration: empty }));

    expect(computePlan({ tree, declaration: empty }).status).toBe('converged');
  });
});

describe('конфликт владения (§4 контракта)', () => {
  it('чужой файл не перезаписывается молча — отказ с внятным сообщением', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
      existing: { [WORKFLOW]: 'name: написано руками\n' },
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.steps).toEqual([]);
    expect(plan.status).toBe('blocked');
    expect(plan.conflicts[0]).toMatchObject({
      kind: 'foreign-dest',
      dest: WORKFLOW,
      detail: { resolution: 'confirm' },
    });
    expect(plan.conflicts[0].message).toContain('конфликт владения');
    expect(tree.read(WORKFLOW, 'utf-8')).toBe('name: написано руками\n');
  });

  it('перезапись возможна только поимённым подтверждением', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
      existing: { [WORKFLOW]: 'name: написано руками\n' },
    });

    const plan = computePlan({ tree, declaration, confirm: [WORKFLOW] });

    expect(plan.status).toBe('pending');
    expect(plan.steps[0]).toMatchObject({ kind: 'update', reason: 'adopted' });
  });

  it('согласие не масштабируется само: соседний отказ остаётся в силе', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry, ignoreEntry],
      sources: SOURCES,
      existing: {
        [WORKFLOW]: 'name: написано руками\n',
        '.gitignore': 'моё\n',
      },
    });

    const plan = computePlan({ tree, declaration, confirm: [WORKFLOW] });

    expect(plan.status).toBe('blocked');
    expect(plan.conflicts.map((conflict) => conflict.dest)).toEqual([
      '.gitignore',
    ]);
  });

  it('подтверждение, которое не понадобилось, названо извещением', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
    });

    const plan = computePlan({
      tree,
      declaration,
      confirm: [WORKFLOW, 'нет/такого.yml'],
    });

    expect(
      plan.notices.map((notice) => [notice.dest, notice.detail.confirmation]),
    ).toEqual([
      [WORKFLOW, 'not-required'],
      ['нет/такого.yml', 'not-declared'],
    ]);
  });

  it('два объявления одного dest — отказ, а не «последний победил»', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry, { ...exactEntry, src: 'ci/other.yml' }],
      sources: { ...SOURCES, 'ci/other.yml': 'name: other\n' },
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.conflicts.map((conflict) => conflict.kind)).toEqual([
      'duplicate-dest',
    ]);
    expect(plan.steps).toEqual([]);
  });

  it('класс файла без маркера не берётся во владение молча', () => {
    const { tree, declaration } = createWorkspace({
      frame: [{ src: 'LICENSE', dest: 'LICENSE' }],
      sources: { LICENSE: 'MIT\n' },
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.conflicts[0]).toMatchObject({
      kind: 'unmarkable-dest',
      dest: 'LICENSE',
      detail: { unmarkable: 'no-format-for-class' },
    });
  });

  it('JSON без объекта в корне — отказ по форме содержимого', () => {
    const { tree, declaration } = createWorkspace({
      frame: [{ src: 'list.json', dest: 'list.json' }],
      sources: { 'list.json': '[1,2]\n' },
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.conflicts[0]).toMatchObject({
      kind: 'unmarkable-dest',
      detail: { unmarkable: 'content-shape' },
    });
  });

  it('отсутствующий шаблон называет полный путь', () => {
    const { tree, declaration } = createWorkspace({ frame: [exactEntry] });

    const plan = computePlan({ tree, declaration });

    expect(plan.conflicts[0]).toMatchObject({ kind: 'missing-source' });
    expect(plan.conflicts[0].message).toContain(`${CONTENT_ROOT}/ci/build.yml`);
  });
});

/**
 * «Нечего делать» и «сошлось» — разные состояния. Гейт вяжет exit-код к
 * сходимости, и зелёный гейт на нерешённом конфликте владения опаснее
 * отсутствующего.
 */
describe('сходимость отделена от пустоты', () => {
  it('план без шагов, но с конфликтом, сходимости НЕ означает', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
      existing: { [WORKFLOW]: 'name: написано руками\n' },
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.steps).toEqual([]);
    expect(plan.conflicts).toHaveLength(1);
    expect(plan.status).toBe('blocked');
    expect(isApplicable(plan)).toBe(false);
  });

  it('признака «в плане нет шагов» в схеме нет — сходимость нельзя получить случайно', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
      existing: { [WORKFLOW]: 'name: написано руками\n' },
    });

    const plan = computePlan({ tree, declaration });

    expect(Object.keys(plan)).not.toContain('empty');
    expect(Object.keys(plan)).not.toContain('applicable');
  });

  it('сошлось — это отсутствие и шагов, и конфликтов', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));

    const plan = computePlan({ tree, declaration });

    expect(plan.status).toBe('converged');
    expect(isApplicable(plan)).toBe(true);
  });
});

/**
 * «Файл разошёлся с шаблоном» и «файл впервые взят под управление» — разные
 * события, и гейт обязан показывать их по-разному.
 */
describe('причина шага обязана быть правдой', () => {
  it('чужой файл под подтверждением берётся с причиной adopted', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
      existing: { [WORKFLOW]: 'name: написано руками\n' },
    });

    const plan = computePlan({ tree, declaration, confirm: [WORKFLOW] });

    expect(plan.steps[0]).toMatchObject({ reason: 'adopted' });
  });

  it('расхождение уже помеченного файла остаётся diverged', () => {
    const { tree, declaration } = createWorkspace({
      frame: [ignoreEntry],
      sources: SOURCES,
    });
    applyPlan(tree, computePlan({ tree, declaration }));
    tree.write(
      '.gitignore',
      (tree.read('.gitignore', 'utf-8') as string).replace('dist', 'build'),
    );

    const plan = computePlan({ tree, declaration });

    expect(plan.steps[0]).toMatchObject({ reason: 'diverged' });
  });

  it('смена объявленного src приводит служебную запись — причина reclaimed', () => {
    // Запись обязана утверждать ровно то, что объявляет декларация СЕЙЧАС, —
    // даже когда содержимое совпало и шага по телу не требуется.
    const { tree, declaration } = createWorkspace({
      frame: [ignoreEntry],
      sources: { ...SOURCES, 'repo/gitignore-2': SOURCES['repo/gitignore'] },
    });
    applyPlan(tree, computePlan({ tree, declaration }));
    expect(readOwnership(tree, '.gitignore')).toEqual({
      src: 'repo/gitignore',
    });

    const next = redeclare(tree, [
      { src: 'repo/gitignore-2', dest: '.gitignore' },
    ]);
    const plan = computePlan({ tree, declaration: next });

    expect(plan.steps[0]).toMatchObject({
      kind: 'update',
      reason: 'reclaimed',
    });

    applyPlan(tree, plan);
    expect(readOwnership(tree, '.gitignore')).toEqual({
      src: 'repo/gitignore-2',
    });
    expect(computePlan({ tree, declaration: next }).status).toBe('converged');
  });
});

/**
 * Приёмочный критерий: любую операцию можно вызвать программно и получить
 * полный результат ДАННЫМИ, ни разу не разобрав текст.
 */
describe('вывод машинночитаем в первую очередь', () => {
  it('каждая причина отказа доступна кодом и данными, а не только текстом', () => {
    const { tree, declaration } = createWorkspace({
      frame: [
        exactEntry,
        { ...exactEntry, src: 'ci/other.yml' },
        { src: 'ci/missing.yml', dest: 'ci/missing.yml' },
        { src: 'ci/build.yml', dest: 'LICENSE' },
        { src: 'ci/build.yml', dest: `${CONTENT_ROOT}/ci/build.yml` },
      ],
      sources: { ...SOURCES, 'ci/other.yml': 'name: other\n' },
    });

    const plan = computePlan({ tree, declaration });
    const byKind = new Map(
      plan.conflicts.map((conflict) => [conflict.kind, conflict]),
    );

    expect(byKind.get('duplicate-dest')?.detail).toEqual({
      claimedBy: 'ci/build.yml',
    });
    expect(byKind.get('missing-source')?.detail).toEqual({
      sourcePath: `${CONTENT_ROOT}/ci/missing.yml`,
    });
    expect(byKind.get('unmarkable-dest')?.detail).toEqual({
      unmarkable: 'no-format-for-class',
    });
    expect(byKind.get('dest-in-content-root')?.detail).toEqual({
      contentRoot: CONTENT_ROOT,
    });
  });

  it('план и отчёт переживают сериализацию: решение принимается без парсинга текста', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry, ignoreEntry, docEntry],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });
    const report = applyPlan(tree, plan);
    const wire = JSON.parse(JSON.stringify({ plan, report }));

    expect(wire.plan.schemaVersion).toBe(plan.schemaVersion);
    expect(wire.report.schemaVersion).toBe(plan.schemaVersion);
    expect(wire.plan.status).toBe('pending');
    expect(
      wire.plan.steps.map((step: { kind: string; reason: string }) => [
        step.kind,
        step.reason,
      ]),
    ).toEqual([
      ['create', 'missing'],
      ['create', 'missing'],
      ['create', 'missing'],
    ]);
    expect(wire.report.applied).toHaveLength(3);
    expect(wire.report.trace[0].name).toBe('apply.steps');
  });

  it('версия схемы вывода поднята: форма несовместима с прежней', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
    });

    expect(computePlan({ tree, declaration }).schemaVersion).toBe(2);
  });

  it('трейсы — именованные спаны с длительностью и атрибутами', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    for (const span of plan.trace) {
      expect(typeof span.name).toBe('string');
      expect(typeof span.ms).toBe('number');
    }
    expect(
      plan.trace.find((span) => span.name === 'plan.owned')?.detail,
    ).toEqual({ files: 0 });
  });
});

/**
 * Атомарность движка кончается на виртуальном дереве: сброс на реальную ФС
 * делает раннер, и его сбой происходит уже ВНЕ журнала отката. Поэтому всё,
 * что упадёт при записи на диск, обязано быть поймано ПЛАНОМ.
 */
describe('объявленное состояние обязано быть физически достижимым', () => {
  it('dest внутри пути другого dest — конфликт плана, а не сходимость', () => {
    const { tree, declaration } = createWorkspace({
      frame: [
        { src: 'ci/build.yml', dest: 'cfg.yml' },
        { src: 'ci/build.yml', dest: 'cfg.yml/inner.yml' },
      ],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.status).toBe('blocked');
    expect(plan.conflicts[0]).toMatchObject({
      kind: 'unreachable-dest',
      dest: 'cfg.yml/inner.yml',
      detail: { blockedBy: 'cfg.yml', collision: 'declared-dest' },
    });
    expect(plan.steps.map((step) => step.dest)).toEqual(['cfg.yml']);
  });

  it('порядок объявления не спасает: вложенный объявлен первым — отказ у внешнего', () => {
    const { tree, declaration } = createWorkspace({
      frame: [
        { src: 'ci/build.yml', dest: 'cfg.yml/inner.yml' },
        { src: 'ci/build.yml', dest: 'cfg.yml' },
      ],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.conflicts[0]).toMatchObject({
      kind: 'unreachable-dest',
      dest: 'cfg.yml',
      detail: { blockedBy: 'cfg.yml/inner.yml', collision: 'declared-dest' },
    });
  });

  it('родительский путь занят ЧУЖИМ файлом в дереве — конфликт плана', () => {
    const { tree, declaration } = createWorkspace({
      frame: [{ src: 'ci/build.yml', dest: 'cfg.yml/inner.yml' }],
      sources: SOURCES,
      existing: { 'cfg.yml': 'настройка: продукта\n' },
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.status).toBe('blocked');
    expect(plan.conflicts[0]).toMatchObject({
      kind: 'unreachable-dest',
      detail: { blockedBy: 'cfg.yml', collision: 'existing-file' },
    });
    expect(tree.read('cfg.yml', 'utf-8')).toBe('настройка: продукта\n');
  });

  it('коллизия отбивается ПО СУЩЕСТВУ, а не побочно правилом про маркер', () => {
    // `cfg` без расширения маркер нести не может, и раньше пара отбивалась
    // именно этим. Побочная защита отвалится, как только класс станет
    // размечаемым, — значит проверка обязана стоять по существу.
    const { tree, declaration } = createWorkspace({
      frame: [
        { src: 'ci/build.yml', dest: 'cfg' },
        { src: 'ci/build.yml', dest: 'cfg/inner.yml' },
      ],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    expect(
      plan.conflicts.find((conflict) => conflict.dest === 'cfg/inner.yml'),
    ).toMatchObject({
      kind: 'unreachable-dest',
      detail: { blockedBy: 'cfg', collision: 'declared-dest' },
    });
  });

  it('dest, чей путь занят ЧУЖИМ каталогом, — тот же класс недостижимости', () => {
    const { tree, declaration } = createWorkspace({
      frame: [{ src: 'ci/build.yml', dest: 'cfg' }],
      sources: SOURCES,
      existing: { 'cfg/inner.yml': 'настройка: продукта\n' },
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.status).toBe('blocked');
    expect(plan.conflicts[0]).toMatchObject({
      kind: 'unreachable-dest',
      dest: 'cfg',
      detail: { blockedBy: 'cfg', collision: 'existing-directory' },
    });
  });

  it('dest внутри contentRoot отбивается по существу, а не как чужой файл', () => {
    const { tree, declaration } = createWorkspace({
      frame: [{ src: 'ci/build.yml', dest: `${CONTENT_ROOT}/ci/build.yml` }],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.conflicts[0]).toMatchObject({
      kind: 'dest-in-content-root',
      detail: { contentRoot: CONTENT_ROOT },
    });
    expect(plan.steps).toEqual([]);
  });
});

describe('охват скана', () => {
  it('сужение охвата раннером названо извещением уровня прогона', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
    });

    const plan = computePlan({
      tree,
      declaration,
      scan: { roots: ['.github'], ignore: [...DEFAULT_SCAN_IGNORE, 'vendor'] },
    });

    expect(plan.notices[0]).toMatchObject({
      kind: 'scan-scope-narrowed',
      detail: { roots: ['.github'], ignored: ['vendor'] },
    });
    expect(plan.notices[0].dest).toBeUndefined();
  });

  it('полный охват извещения не порождает', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.notices).toEqual([]);
  });
});

describe('трейсы', () => {
  it('план несёт замеры этапов', () => {
    const { tree, declaration } = createWorkspace({
      frame: [exactEntry],
      sources: SOURCES,
    });

    const plan = computePlan({ tree, declaration });

    expect(plan.trace.map((span) => span.name)).toEqual([
      'plan.scan-ownership',
      'plan.owned',
      'plan.frame',
      'plan.orphans',
    ]);
    expect(
      plan.trace.find((span) => span.name === 'plan.frame')?.detail,
    ).toEqual({ entries: 1 });
  });
});
